In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv("/content/winequality.csv",sep=";")

In [ ]:
data.head(20)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.70,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.60,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.90,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.50,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.50,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
5,8.1,0.28,0.40,6.90,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
6,6.2,0.32,0.16,7.00,0.045,30.0,136.0,0.9949,3.18,0.47,9.6,6
7,7.0,0.27,0.36,20.70,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
8,6.3,0.30,0.34,1.60,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
9,8.1,0.22,0.43,1.50,0.044,28.0,129.0,0.9938,3.22,0.45,11.0,6


In [ ]:
data.isna().sum()

,0
fixed acidity,0
volatile acidity,0
citric acid,0
residual sugar,0
chlorides,0
free sulfur dioxide,0
total sulfur dioxide,0
density,0
pH,0
sulphates,0


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [ ]:
new_df=data[data['quality'].isin([5,6,7])]
new_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6


In [ ]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4535 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4535 non-null   float64
 1   volatile acidity      4535 non-null   float64
 2   citric acid           4535 non-null   float64
 3   residual sugar        4535 non-null   float64
 4   chlorides             4535 non-null   float64
 5   free sulfur dioxide   4535 non-null   float64
 6   total sulfur dioxide  4535 non-null   float64
 7   density               4535 non-null   float64
 8   pH                    4535 non-null   float64
 9   sulphates             4535 non-null   float64
 10  alcohol               4535 non-null   float64
 11  quality               4535 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 460.6 KB


In [ ]:
new_df['quality'].value_counts()

,count
quality,
6,2198
5,1457
7,880


In [ ]:
X = new_df.drop("quality", axis=1)

y = new_df["quality"]

In [ ]:
new_df.groupby("quality").count()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
5,1457,1457,1457,1457,1457,1457,1457,1457,1457,1457,1457
6,2198,2198,2198,2198,2198,2198,2198,2198,2198,2198,2198
7,880,880,880,880,880,880,880,880,880,880,880


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(

    X, y, test_size=0.2, random_state=0

)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
X_train

array([[ 0.54460045,  1.63662349,  0.28925438, ...,  0.2756489 ,
        -0.54254348,  2.25337036],
       [ 0.54460045, -0.15526017, -0.12655309, ..., -0.78323983,
        -0.36510296,  1.26295822],
       [-0.54310141,  0.89878904, -1.124491  , ...,  0.34182945,
        -0.54254348, -0.80040039],
       ...,
       [-1.02652446, -0.15526017, -0.37603757, ...,  1.26835709,
        -0.45382322,  1.51056126],
       [-1.26823599, -0.57687986, -0.37603757, ..., -0.31997601,
        -1.16358533,  0.52014912],
       [-0.18053412,  0.89878904, -0.62552205, ..., -1.31268419,
        -1.69590691,  1.42802691]])

In [ ]:
X_test

array([[ 0.0611774 , -0.89309462,  0.45557736, ..., -0.51851764,
         1.49802257,  0.27254609],
       [-0.9056687 , -0.68228478, -0.29287607, ...,  0.54037109,
        -1.60718665,  1.84069864],
       [-0.42224565, -1.20930938, -0.04339159, ...,  0.73891273,
        -0.89742454,  0.76775216],
       ...,
       [-1.8725148 ,  1.26770627, -2.20559041, ...,  2.06252364,
        -1.25230559,  0.1074774 ],
       [-0.66395718, -0.04985525, -1.29081399, ...,  0.2756489 ,
        -0.18766243, -1.21307211],
       [ 0.42374469,  1.32040873,  1.28719229, ..., -1.1803231 ,
        -0.63126375, -0.96546908]])

In [ ]:
ypred=classifier.predict(X_test)

In [ ]:
ypred

array([7, 7, 7, 5, 7, 7, 6, 7, 5, 5, 7, 5, 5, 7, 6, 5, 5, 7, 7, 7, 6, 5,
       5, 7, 6, 7, 7, 7, 7, 7, 7, 6, 7, 6, 7, 6, 5, 7, 7, 7, 5, 6, 7, 7,
       7, 7, 6, 5, 6, 5, 5, 6, 7, 5, 7, 6, 7, 7, 6, 7, 5, 6, 6, 6, 5, 5,
       5, 7, 5, 6, 7, 7, 6, 6, 6, 5, 7, 7, 7, 5, 7, 6, 7, 6, 5, 6, 5, 6,
       6, 6, 5, 7, 6, 5, 5, 7, 7, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 7, 6, 5,
       7, 5, 6, 5, 6, 5, 6, 5, 6, 7, 5, 7, 7, 7, 7, 7, 5, 5, 7, 6, 7, 5,
       6, 5, 6, 5, 7, 5, 5, 7, 7, 7, 7, 6, 5, 5, 6, 5, 6, 5, 7, 5, 5, 7,
       7, 6, 6, 6, 5, 5, 6, 6, 6, 7, 6, 7, 7, 5, 6, 6, 6, 7, 5, 6, 6, 6,
       7, 7, 7, 5, 7, 6, 5, 6, 5, 6, 6, 7, 5, 6, 6, 7, 7, 6, 7, 7, 7, 7,
       5, 7, 6, 5, 7, 7, 6, 5, 5, 6, 6, 7, 7, 6, 6, 5, 6, 6, 5, 5, 6, 5,
       5, 5, 7, 6, 7, 5, 6, 7, 7, 5, 5, 5, 7, 6, 5, 5, 5, 7, 6, 5, 5, 5,
       6, 6, 5, 6, 6, 7, 6, 6, 6, 6, 6, 6, 7, 6, 5, 7, 5, 7, 7, 6, 5, 5,
       7, 5, 5, 7, 7, 7, 7, 5, 7, 7, 7, 6, 7, 6, 6, 6, 7, 5, 6, 7, 5, 7,
       5, 7, 7, 6, 6, 5, 7, 5, 7, 7, 7, 5, 5, 7, 5,

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,ypred)
print(cm)


[[171 100  31]
 [117 150 162]
 [ 14  35 127]]


In [ ]:
accuracy_score(y_test,ypred)

0.49393605292171994

In [ ]:
ypred.shape

(907,)

In [ ]:
Results=pd.DataFrame(columns=['Actual','Predicted'])
Results['Actual']=y_test
Results['Predicted']=ypred
Results.head(25)

,Actual,Predicted
2015,6,7
3858,6,7
4599,7,7
410,6,5
2624,5,7
2118,6,7
78,5,6
2281,6,7
2546,5,5
1507,6,5
